name: Update Rules
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update Rules
        run: |
          bash ./utils/deduplication.sh
      - name: Git push assets to Github
        run: |
          git config --local user.name "Luphraim"
          git config --local user.email "Luphraim@outlook.com"
          git branch -m main
          git add --all
          git commit -m "Auto Updated at $(date)"
          git fetch --unshallow origin
          git push -u -f origin --all
